// Generated from date-specific Airbnb research. Run npm run build:airbnb after source updates.
export const airbnbSearch = {
  "checkedAt": "2026-09-01",
  "stay": "2027-03-21부터 03-31, 10박",
  "guests": "성인 6명, 어린이 3명, 총 9명",
  "searchUrl": "https://www.airbnb.com/s/Istanbul--Turkiye/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&date_picker_type=calendar&checkin=2027-03-21&checkout=2027-03-31&adults=6&children=3",
  "caveat": "목표 날짜, 9인, 10박으로 예약 버튼과 원화 총액이 함께 보인 12곳만 가격 확인으로 분류했습니다. 3곳은 날짜 또는 최소 숙박일 때문에 제외했습니다. 실시간 재고와 총액은 결제 전에 다시 확인해야 합니다.",
  "exactAvailableCount": 12,
  "unavailableCount": 3,
  "lowestExactTotal": 2469835,
  "highestExactTotal": 15897219,
  "options": [
    {
      "rank": 1,
      "id": "airbnb-31092297",
      "listingId": "31092297",
      "name": "Penthouse 4BR, Terrace, Bosphorus View",
      "neighborhood": "카바타쉬, 돌마바흐체 앞",
      "capacity": 11,
      "bedrooms": 4,
      "beds": 5,
      "baths": 2,
      "rating": 4.83,
      "reviews": 454,
      "fit": "상",
      "reason": "침실 4개와 욕실 2개를 한 층에서 쓴다. 보스포루스와 카바타쉬 교통이 가깝다.",
      "caution": "침실 침대는 8명분이다. 아홉 번째 사람은 거실 소파를 써야 한다. 거리에서 엘리베이터까지 계단 26개가 있다.",
      "availability": "available_exact",
      "availabilityEvidence": "10 nights, 9 guests, Reserve 버튼이 함께 표시됐다.",
      "availabilityLimit": "실시간 재고이므로 결제 전 달라질 수 있다.",
      "exactTotal": 6026212,
      "nightlyAverage": 602621,
      "price": "6,026,212원",
      "priceEvidence": "가격 내역에는 10박 숙박료, 주간 할인과 총액만 표시됐다.",
      "taxesAndFees": "세금과 서비스 수수료 별도 내역 미표시",
      "cancellation": "2월 19일 전까지 무료 취소다. 3월 14일 전까지는 일부 환불이다.",
      "cancellationStatus": "displayed",
      "cancellationLimit": "전체 약관의 세부 공제액은 화면에 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": "2027-02-19",
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/31092297?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 2,
      "id": "airbnb-1585341457182878132",
      "listingId": "1585341457182878132",
      "name": "Premium Family Home for 10, Near Taksim, 4BR",
      "neighborhood": "시슬리, 탁심역에서 약 750m",
      "capacity": 10,
      "bedrooms": 4,
      "beds": 5,
      "baths": 3,
      "rating": 4.86,
      "reviews": 21,
      "fit": "상",
      "reason": "침실 4개와 욕실 3개를 단독 주택에서 쓴다. 확인된 예약 가능 후보 가운데 총액이 가장 낮다.",
      "caution": "침실 침대는 8명분이다. 아홉 번째 사람은 거실을 써야 한다. 주방은 간단한 조리용이라 아홉 명의 저녁 준비에는 작다.",
      "availability": "available_exact",
      "availabilityEvidence": "10 nights, 9 guests, Reserve 버튼이 함께 표시됐다.",
      "availabilityLimit": "실시간 재고이므로 결제 전 달라질 수 있다.",
      "exactTotal": 2469835,
      "nightlyAverage": 246984,
      "price": "2,469,835원",
      "priceEvidence": "가격 내역에는 10박 숙박료, 주간 할인과 총액만 표시됐다.",
      "taxesAndFees": "세금과 서비스 수수료 별도 내역 미표시",
      "cancellation": "3월 7일 전까지 무료 취소다. 3월 14일 전까지는 일부 환불이다.",
      "cancellationStatus": "displayed",
      "cancellationLimit": "전체 약관의 세부 공제액은 화면에 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": "2027-03-07",
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/1585341457182878132?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 3,
      "id": "airbnb-733361398293897874",
      "listingId": "733361398293897874",
      "name": "Artistically Renovated Triplex Villa 400m2 Ortaköy",
      "neighborhood": "베식타시, 오르타쾨이",
      "capacity": 10,
      "bedrooms": 4,
      "beds": 6,
      "baths": 3,
      "rating": 4.94,
      "reviews": 139,
      "fit": "상",
      "reason": "침실 4개와 욕실 3개를 갖췄다. 아이용 침대 2개와 아기 욕조도 있다. 오르타쾨이 해안까지 약 500m다.",
      "caution": "3층 주택이라 매일 계단을 써야 한다. 아홉 번째 사람은 거실 소파베드를 쓴다.",
      "availability": "available_exact",
      "availabilityEvidence": "10 nights, 9 guests, Reserve 버튼이 함께 표시됐다.",
      "availabilityLimit": "실시간 재고이므로 결제 전 달라질 수 있다.",
      "exactTotal": 5288210,
      "nightlyAverage": 528821,
      "price": "5,288,210원",
      "priceEvidence": "가격 내역에는 10박 숙박료, 주간 할인과 총액만 표시됐다.",
      "taxesAndFees": "세금과 서비스 수수료 별도 내역 미표시",
      "cancellation": "3월 16일 전까지 무료 취소다. 체크인 전까지는 일부 환불이다.",
      "cancellationStatus": "displayed",
      "cancellationLimit": "전체 약관의 세부 공제액은 화면에 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": "2027-03-16",
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/733361398293897874?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 4,
      "id": "airbnb-1283892058506904338",
      "listingId": "1283892058506904338",
      "name": "3 Master BR Apt with Sea View",
      "neighborhood": "파티흐, 구시가지 해안",
      "capacity": 9,
      "bedrooms": 3,
      "beds": 6,
      "baths": 3,
      "rating": 4.94,
      "reviews": 67,
      "fit": "중",
      "reason": "침실 3개에 욕실 3개라 아침 준비가 빠르다. 한 욕실에는 욕조가 있다.",
      "caution": "침실 수는 세 가족이 각각 한 방을 쓰는 수준이다. 공용 테라스는 다른 투숙객과 함께 쓴다.",
      "availability": "available_exact",
      "availabilityEvidence": "10 nights, 9 guests, Reserve 버튼이 함께 표시됐다.",
      "availabilityLimit": "실시간 재고이므로 결제 전 달라질 수 있다.",
      "exactTotal": 6565896,
      "nightlyAverage": 656590,
      "price": "6,565,896원",
      "priceEvidence": "가격 내역에는 10박 숙박료, 주간 할인과 총액만 표시됐다.",
      "taxesAndFees": "세금과 서비스 수수료 별도 내역 미표시",
      "cancellation": "3월 20일 전까지 무료 취소다. 체크인 전까지는 일부 환불이다.",
      "cancellationStatus": "displayed",
      "cancellationLimit": "전체 약관의 세부 공제액은 화면에 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": "2027-03-20",
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/1283892058506904338?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 5,
      "id": "airbnb-1248360830079976262",
      "listingId": "1248360830079976262",
      "name": "Amazing Sea View Flat in Karaköy, 4BR, 5AC, 2BA",
      "neighborhood": "베요을루, 카라쾨이",
      "capacity": 10,
      "bedrooms": 4,
      "beds": 6,
      "baths": 2,
      "rating": 4.64,
      "reviews": 25,
      "fit": "상",
      "reason": "카라쾨이에서 트램과 페리를 바로 쓸 수 있다. 침실 4개와 욕실 2개를 갖췄다.",
      "caution": "평점은 4.64로 상위 후보보다 낮다. 거리 소음과 청결을 지적한 후기 항목이 보인다.",
      "availability": "available_exact",
      "availabilityEvidence": "10 nights, 9 guests, Reserve 버튼이 함께 표시됐다.",
      "availabilityLimit": "실시간 재고이므로 결제 전 달라질 수 있다.",
      "exactTotal": 5034695,
      "nightlyAverage": 503470,
      "price": "5,034,695원",
      "priceEvidence": "가격 내역에는 10박 숙박료, 주간 할인과 총액만 표시됐다.",
      "taxesAndFees": "세금과 서비스 수수료 별도 내역 미표시",
      "cancellation": "3월 7일 전까지 무료 취소다. 3월 14일 전까지는 일부 환불이다.",
      "cancellationStatus": "displayed",
      "cancellationLimit": "전체 약관의 세부 공제액은 화면에 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": "2027-03-07",
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/1248360830079976262?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 6,
      "id": "airbnb-1665364785885022959",
      "listingId": "1665364785885022959",
      "name": "4BR Apt In Old City, Terrace, Hot Tub, AC, Wifi",
      "neighborhood": "파티흐, 구시가지",
      "capacity": 10,
      "bedrooms": 4,
      "beds": 6,
      "baths": 1.5,
      "rating": 5,
      "reviews": 12,
      "fit": "조건부",
      "reason": "구시가지 주요 명소까지 도보 10분에서 15분권이라고 숙소가 설명한다. 침실 4개와 루프톱 공간이 있다.",
      "caution": "욕실이 1.5개라 아홉 명의 아침 준비가 느려질 수 있다. 후기 수는 12개로 적다.",
      "availability": "available_exact",
      "availabilityEvidence": "10 nights, 9 guests, Reserve 버튼이 함께 표시됐다.",
      "availabilityLimit": "실시간 재고이므로 결제 전 달라질 수 있다.",
      "exactTotal": 3677403,
      "nightlyAverage": 367740,
      "price": "3,677,403원",
      "priceEvidence": "가격 내역에는 10박 숙박료, 주간 할인과 총액만 표시됐다.",
      "taxesAndFees": "세금과 서비스 수수료 별도 내역 미표시",
      "cancellation": "3월 16일 전까지 무료 취소다. 체크인 전까지는 일부 환불이다.",
      "cancellationStatus": "displayed",
      "cancellationLimit": "전체 약관의 세부 공제액은 화면에 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": "2027-03-16",
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/1665364785885022959?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 7,
      "id": "airbnb-1751016276471845889",
      "listingId": "1751016276471845889",
      "name": "3BR Ocean House 9 Guests Prime Location",
      "neighborhood": "베요을루, 탁심광장에서 도보 1분에서 2분",
      "capacity": 9,
      "bedrooms": 3,
      "beds": 6,
      "baths": 2,
      "rating": null,
      "reviews": 0,
      "fit": "중",
      "reason": "탁심광장과 지하철이 가까워 이동이 짧다. 침실마다 에어컨이 있고 엘리베이터가 있다.",
      "caution": "침실은 8명분이다. 아홉 번째 사람은 거실 소파를 쓴다. 신규 숙소라 축적된 후기가 없다.",
      "availability": "available_exact",
      "availabilityEvidence": "10 nights, 9 guests, Reserve 버튼이 함께 표시됐다.",
      "availabilityLimit": "실시간 재고이므로 결제 전 달라질 수 있다.",
      "exactTotal": 3785143,
      "nightlyAverage": 378514,
      "price": "3,785,143원",
      "priceEvidence": "가격 내역에는 10박 숙박료, 주간 할인과 총액만 표시됐다.",
      "taxesAndFees": "세금과 서비스 수수료 별도 내역 미표시",
      "cancellation": "3월 16일 전까지 무료 취소다. 체크인 전까지는 일부 환불이다.",
      "cancellationStatus": "displayed",
      "cancellationLimit": "전체 약관의 세부 공제액은 화면에 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": "2027-03-16",
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/1751016276471845889?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 8,
      "id": "airbnb-37868735",
      "listingId": "37868735",
      "name": "Spacious 3BR, Bosphorus and Dolmabahçe View",
      "neighborhood": "카바타쉬, 돌마바흐체 앞",
      "capacity": 9,
      "bedrooms": 3,
      "beds": 4,
      "baths": 2,
      "rating": 4.85,
      "reviews": 370,
      "fit": "중",
      "reason": "돌마바흐체 앞에서 페리와 트램을 함께 쓰기 쉽다. 욕실은 2개다.",
      "caution": "침실 세 곳은 6명분이다. 나머지 3명은 거실 소파와 카우치를 써야 한다.",
      "availability": "available_exact",
      "availabilityEvidence": "10 nights, 9 guests, Reserve 버튼이 함께 표시됐다.",
      "availabilityLimit": "실시간 재고이므로 결제 전 달라질 수 있다.",
      "exactTotal": 4734342,
      "nightlyAverage": 473434,
      "price": "4,734,342원",
      "priceEvidence": "가격 내역에는 10박 숙박료, 주간 할인과 총액만 표시됐다.",
      "taxesAndFees": "세금과 서비스 수수료 별도 내역 미표시",
      "cancellation": "2월 19일 전까지 무료 취소다. 3월 14일 전까지는 일부 환불이다.",
      "cancellationStatus": "displayed",
      "cancellationLimit": "전체 약관의 세부 공제액은 화면에 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": "2027-02-19",
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/37868735?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 9,
      "id": "airbnb-886052227843874450",
      "listingId": "886052227843874450",
      "name": "Taksim Square, Unique Penthouse for 12, 5BR",
      "neighborhood": "베요을루, 탁심광장에서 약 250m",
      "capacity": 12,
      "bedrooms": 5,
      "beds": 6,
      "baths": 2,
      "rating": 4.49,
      "reviews": 35,
      "fit": "상",
      "reason": "침실 5개라 가족별 사생활을 나누기 쉽다. 탁심역이 가깝고 엘리베이터가 있다.",
      "caution": "한 집이 아니라 같은 건물 3층과 4층의 두 아파트를 묶은 상품이다. 평점은 4.49다.",
      "availability": "available_exact",
      "availabilityEvidence": "10 nights, 9 guests, Reserve 버튼이 함께 표시됐다.",
      "availabilityLimit": "실시간 재고이므로 결제 전 달라질 수 있다.",
      "exactTotal": 4778382,
      "nightlyAverage": 477838,
      "price": "4,778,382원",
      "priceEvidence": "가격 내역에는 10박 숙박료, 주간 할인과 총액만 표시됐다.",
      "taxesAndFees": "세금과 서비스 수수료 별도 내역 미표시",
      "cancellation": "3월 16일 전까지 무료 취소다. 체크인 전까지는 일부 환불이다.",
      "cancellationStatus": "displayed",
      "cancellationLimit": "전체 약관의 세부 공제액은 화면에 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": "2027-03-16",
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/886052227843874450?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 10,
      "id": "airbnb-1329307242595134008",
      "listingId": "1329307242595134008",
      "name": "Spacious 4+1 Sea and Mosque View Apartment in Sultanahmet",
      "neighborhood": "파티흐, 술탄아흐메트",
      "capacity": 9,
      "bedrooms": 4,
      "beds": 6,
      "baths": 2,
      "rating": 4.41,
      "reviews": 17,
      "fit": "상",
      "reason": "술탄아흐메트에서 구시가지 일정을 도보로 시작할 수 있다. 침실 4개와 욕실 2개다.",
      "caution": "평점은 4.41로 낮다. 후기 수가 17개라 품질 편차를 더 확인해야 한다.",
      "availability": "available_exact",
      "availabilityEvidence": "10 nights, 9 guests, Reserve 버튼이 함께 표시됐다.",
      "availabilityLimit": "실시간 재고이므로 결제 전 달라질 수 있다.",
      "exactTotal": 7309560,
      "nightlyAverage": 730956,
      "price": "7,309,560원",
      "priceEvidence": "가격 내역에는 10박 숙박료, 주간 할인과 총액만 표시됐다.",
      "taxesAndFees": "세금과 서비스 수수료 별도 내역 미표시",
      "cancellation": "3월 16일 전까지 무료 취소다. 체크인 전까지는 일부 환불이다.",
      "cancellationStatus": "displayed",
      "cancellationLimit": "전체 약관의 세부 공제액은 화면에 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": "2027-03-16",
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/1329307242595134008?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 11,
      "id": "airbnb-1150573948484205391",
      "listingId": "1150573948484205391",
      "name": "Large and Private Apartment for 9 People in the Center of Şişli",
      "neighborhood": "시슬리 중심부",
      "capacity": 9,
      "bedrooms": 4,
      "beds": 7,
      "baths": 1,
      "rating": 4.75,
      "reviews": null,
      "fit": "조건부",
      "reason": "침실 4개에 침대 7개라 아홉 명을 침실 안에 배치할 수 있다. 시슬리의 식당과 교통을 이용하기 쉽다.",
      "caution": "욕실이 하나뿐이다. 연기와 일산화탄소 경보기는 숙소가 신고하지 않았다.",
      "availability": "available_exact",
      "availabilityEvidence": "10 nights, 9 guests, Reserve 버튼과 총액이 함께 표시됐다.",
      "availabilityLimit": "실시간 재고이므로 결제 전 달라질 수 있다.",
      "exactTotal": 3523230,
      "nightlyAverage": 352323,
      "price": "3,523,230원",
      "priceEvidence": "예약 패널의 10박 총액은 확인했다. 가격 내역 대화상자는 재검증 중 열리지 않았다.",
      "taxesAndFees": "세금과 서비스 수수료 별도 내역 미표시",
      "cancellation": "3월 20일 전까지 무료 취소다. 체크인 전까지는 일부 환불이다.",
      "cancellationStatus": "displayed",
      "cancellationLimit": "전체 약관의 세부 공제액은 화면에 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": "2027-03-20",
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/1150573948484205391?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 12,
      "id": "airbnb-1155770524163347634",
      "listingId": "1155770524163347634",
      "name": "Waterfront Villa, Sea View, Private Terrace with Dome",
      "neighborhood": "파티흐, 발라트",
      "capacity": 16,
      "bedrooms": 7,
      "beds": 9,
      "baths": 3,
      "rating": 4.83,
      "reviews": 18,
      "fit": "상",
      "reason": "침실 7개와 욕실 3개라 세 가족이 공간을 넉넉히 나눌 수 있다. 전용 테라스와 주차 공간이 있다.",
      "caution": "확인된 후보 가운데 총액이 가장 높다. 아홉 명에게는 침실 7개가 과하고 발라트에서 신시가지까지 차량 이동이 필요하다.",
      "availability": "available_exact",
      "availabilityEvidence": "10 nights, 9 guests, Reserve 버튼이 함께 표시됐다.",
      "availabilityLimit": "실시간 재고이므로 결제 전 달라질 수 있다.",
      "exactTotal": 15897219,
      "nightlyAverage": 1589722,
      "price": "15,897,219원",
      "priceEvidence": "가격 내역에는 10박 숙박료, 주간 할인과 총액만 표시됐다.",
      "taxesAndFees": "세금과 서비스 수수료 별도 내역 미표시",
      "cancellation": "2월 19일 전까지 무료 취소다. 3월 14일 전까지는 일부 환불이다.",
      "cancellationStatus": "displayed",
      "cancellationLimit": "전체 약관의 세부 공제액은 화면에 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": "2027-02-19",
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/1155770524163347634?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 13,
      "id": "airbnb-905809",
      "listingId": "905809",
      "name": "Urban Loft for 12 Guests, 5BR, 3.5 BA, Galata",
      "neighborhood": "베요을루, 갈라타",
      "capacity": 12,
      "bedrooms": 5,
      "beds": 6,
      "baths": 3.5,
      "rating": 4.96,
      "reviews": 85,
      "fit": "제외",
      "reason": "침실 5개와 욕실 3.5개를 갖췄다. 갈라타 지하철과 카라쾨이 트램을 함께 쓰기 쉽다.",
      "caution": "같은 건물의 두 아파트를 묶은 상품이다. 요청 날짜에는 예약할 수 없다.",
      "availability": "unavailable_exact",
      "availabilityEvidence": "Those dates are not available 문구와 Change dates 버튼이 표시됐다.",
      "availabilityLimit": "검색 시점에는 예약할 수 없었다. 취소가 생기면 재고가 바뀔 수 있다.",
      "exactTotal": null,
      "nightlyAverage": null,
      "price": "요청 일정 예약 불가",
      "priceEvidence": "해당 날짜가 막혀 가격이 표시되지 않았다.",
      "taxesAndFees": "가격 미표시",
      "cancellation": "현재 예약 불가 상태라 이 일정의 취소 조건을 확정할 수 없습니다.",
      "cancellationStatus": "displayed_reference_only",
      "cancellationLimit": "해당 날짜는 예약 불가였으므로 실제 결제 가능한 요금의 조건으로 볼 수 없다.",
      "referenceCancellation": "예약 후 24시간은 무료 취소라고 표시됐다. 3월 14일 전까지는 일부 환불이다.",
      "freeCancellationUntil": null,
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/905809?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 14,
      "id": "airbnb-2320332",
      "listingId": "2320332",
      "name": "Scarlet, Queens Color Concept, 3 Bedroom and 4 Bathroom",
      "neighborhood": "베요을루, 이스티클랄 거리에서 도보 약 3분",
      "capacity": 10,
      "bedrooms": 3,
      "beds": 7,
      "baths": 4,
      "rating": 4.7,
      "reviews": 244,
      "fit": "제외",
      "reason": "침실 3개에 욕실 4개라 세 가족이 욕실을 나누기 쉽다. 이스티클랄 거리와 가깝다.",
      "caution": "최소 숙박일이 100박이라 이번 10박 일정에는 맞지 않는다.",
      "availability": "unavailable_exact",
      "availabilityEvidence": "Minimum stay is 100 nights 문구와 Change dates 버튼이 표시됐다.",
      "availabilityLimit": "10박 일정에는 예약할 수 없다. 숙소가 최소 숙박일을 바꾸면 결과가 달라질 수 있다.",
      "exactTotal": null,
      "nightlyAverage": null,
      "price": "요청 일정 예약 불가",
      "priceEvidence": "최소 100박 조건 때문에 가격이 표시되지 않았다.",
      "taxesAndFees": "가격 미표시",
      "cancellation": "현재 예약 불가 상태라 이 일정의 취소 조건을 확정할 수 없습니다.",
      "cancellationStatus": "not_shown",
      "cancellationLimit": "요청 일정의 취소 조건이 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": null,
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/2320332?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    },
    {
      "rank": 15,
      "id": "airbnb-726854148956034383",
      "listingId": "726854148956034383",
      "name": "Luxury Villa, Sleeps 9, Terrace Taksim 4BR and 4BA",
      "neighborhood": "베요을루, 탁심과 지항기르 사이",
      "capacity": 9,
      "bedrooms": 4,
      "beds": 5,
      "baths": 4,
      "rating": 4.76,
      "reviews": 29,
      "fit": "제외",
      "reason": "침실 4개와 욕실 4개를 한 일행이 단독으로 쓴다. 탁심과 지항기르를 걸어서 다니기 쉽다.",
      "caution": "5층 구조라 실내 계단이 많다. 최소 숙박일이 30박이라 이번 일정에는 맞지 않는다.",
      "availability": "unavailable_exact",
      "availabilityEvidence": "Minimum stay is 30 nights 문구와 Change dates 버튼이 표시됐다.",
      "availabilityLimit": "10박 일정에는 예약할 수 없다. 숙소가 최소 숙박일을 바꾸면 결과가 달라질 수 있다.",
      "exactTotal": null,
      "nightlyAverage": null,
      "price": "요청 일정 예약 불가",
      "priceEvidence": "최소 30박 조건 때문에 가격이 표시되지 않았다.",
      "taxesAndFees": "가격 미표시",
      "cancellation": "현재 예약 불가 상태라 이 일정의 취소 조건을 확정할 수 없습니다.",
      "cancellationStatus": "not_shown",
      "cancellationLimit": "요청 일정의 취소 조건이 표시되지 않았다.",
      "referenceCancellation": null,
      "freeCancellationUntil": null,
      "observedAt": "2026-09-01",
      "url": "https://www.airbnb.com/rooms/726854148956034383?check_in=2027-03-21&check_out=2027-03-31&guests=9&adults=6&children=3"
    }
  ]
};
